### ISSUE TITLE
Système d'animation

### ISSUE THREAD

**Issue by ThomasFabrePro** [Craybloge/Spirit-Forest#21]
Voir Thomas pour plus d'infos.
Le système d'animation de Unity est plus pratique que celui qu'on utilise actuellement. Sans rentrer dans les détails il permet de créer un squelette du sprite et de l'animer. Le soucis est qu'aucun fichier du sprite complet n'existe et que certains morceaux de notre code utilisent le sprite (notamment pour le tourner à droite ou à gauche). Du coup lorsqu'on tente d'intégrer ce nouveau système au personnage, plus rien ne fonctionne à cause du composant Sprite Renderer qui ne peux pas être rempli avec le sprite du personnage.
Lien vers le tuto utilisé en premier lieu pour mettre en place ce système : https://www.youtube.com/watch?v=eXIuizGzY2A&list=RDCMUCYbK_tjZ2OrIZFBvU6CCMiA&start_radio=1&t=129&ab_channel=Brackeys

**Comment by CyriaqueSoden** [comment]
finito
